[tox]
envlist = py{311}
[testenv]
conda_channels =
    conda-forge
conda_create_args =
    --override-channels
conda_deps =
    make
    gcc_linux-64
    gfortran_linux-64
setenv =
    PYTHONUNBUFFERED = 1
wheel = true
deps=
    numpy==2.1.1
    pytest
    setuptools
    wheel
    Cython
whitelist_externals = pytest
    /bin/rm
commands =
    pytest -s --log-cli-level=DEBUG -v tkmatrix/tests/
