name: MATRIX tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py:
          - "3.10"
        toxenv:
          - "py310"
        exclude:
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tox
        run: python -m pip install tox tox-wheel
      - name: Run test suite
        run: tox -vv -e "${{ matrix.toxenv }}"
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
